name: Carolina Care Center
favicon: null
layout_spectrum: 0.30931
typography_spectrum: 0.75738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#863b96'
    - '#17b09b'
    - '#d0b7d7'
    - '#a96fb5'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
